# Generated by Django 4.1.7 on 2023-04-11 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_userprofile_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=50)),
                ('T_location', models.DateTimeField(max_length=50)),
                ('team_name', models.DateTimeField(max_length=50)),
                ('C', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroundAdmin',
            fields=[
                ('ga_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ground_name', models.CharField(max_length=100)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('g_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ground_name', models.CharField(max_length=100)),
                ('g_loaction', models.CharField(max_length=100)),
                ('g_type', models.CharField(max_length=100)),
                ('g_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groundadmin')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('start_date_time', models.DateField()),
                ('coaching_duration', models.CharField(max_length=50)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
