# Generated by Django 4.1.7 on 2023-04-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_player_player_type_team_groundadmin_ground_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='G_payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(max_length=50)),
                ('amount', models.FloatField()),
                ('GA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groundadmin')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='C_payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(max_length=50)),
                ('amount', models.FloatField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coach')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField(max_length=50)),
                ('match_time', models.DateTimeField(max_length=50)),
                ('Ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ground')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
    ]
