# Generated by Django 4.1.7 on 2023-05-27 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_remove_c_payment_coach_remove_c_payment_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=300)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=50)),
                ('T_location', models.DateTimeField(max_length=50)),
                ('team_name', models.DateTimeField(max_length=50)),
                ('C', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=20)),
                ('player_type', models.CharField(max_length=20)),
                ('team_name', models.CharField(max_length=50)),
                ('User_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroundAdmin',
            fields=[
                ('ga_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ground_name', models.CharField(max_length=100)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('g_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ground_name', models.CharField(max_length=100)),
                ('g_loaction', models.CharField(max_length=100)),
                ('g_type', models.CharField(max_length=100)),
                ('g_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groundadmin')),
            ],
        ),
        migrations.CreateModel(
            name='G_payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(max_length=50)),
                ('amount', models.FloatField()),
                ('GA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.groundadmin')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('start_date_time', models.DateField()),
                ('coaching_duration', models.CharField(max_length=50)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='C_payment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(max_length=50)),
                ('amount', models.FloatField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coach')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField(max_length=50)),
                ('match_time', models.DateTimeField(max_length=50)),
                ('Ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ground')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
        ),
    ]
