# Generated by Django 4.1.7 on 2023-05-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userprofile_team_player_groundadmin_ground_g_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
