# Generated by Django 4.1.7 on 2023-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_player_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTeamForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('TeamName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='profile_picture',
        ),
    ]
