# Generated by Django 4.1.7 on 2023-05-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_jointeamform_remove_player_profile_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JoinTeamForm',
            new_name='JTForm',
        ),
    ]
