# Generated by Django 4.1.7 on 2023-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_jointeamform_jtform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(max_length=100)),
            ],
        ),
    ]
